c<-read.csv("rainfall.csv",stringsAsFactors = FALSE)
library(dplyr)
library(tseries)
library(forecast)
head(c)
c<-filter(c,SD_Name=="WEST UTTAR PRADESH")
head(c)
tail(c)
c<-filter(c,YEAR<2014)
library(reshape)
str(c)
c<-select(c,YEAR:Oct.Dec)
mel<-melt(c,c("YEAR"))
head(mel)
mel<-arrange(mel,YEAR)
head(mel,20)
q<-"SELECT distinct(variable) FROM mel"
library(sqldf)
res<-sqldf(q)
n<-nrow(res)
rainfall<<-data.frame(month=c(),rain=c())
for(i in 1:n){
  q<-paste("SELECT * FROM mel where variable='",res[i,1],"'",sep="")
  resquery<-sqldf(q)
  melloop<-ts(resquery$value,frequency=1)
  model<-Arima(melloop,order=c(1,0,1),seasonal=list(order=c(1,1,1),period=1),method="CSS")
  pre<-forecast(model,h=1)
  pre<-as.data.frame(pre)
  nextrain<-data.frame(month=res[i,1],rain=pre[1,1])
  rainfall<<-rbind(rainfall,nextrain)
}
write.csv(rainfall,"prediction.csv")
