c<-read.csv("rainfall.csv",stringsAsFactors = FALSE)
library(dplyr)
library(tseries)
library(forecast)
head(c)
c<-filter(c,SD_Name=="WEST UTTAR PRADESH")
head(c)
tail(c)
c<-filter(c,YEAR<2014&YEAR>1949)
library(reshape)
str(c)
c<-select(c,YEAR,JAN:DEC)
mel<-melt(c,c("YEAR"))
head(mel)
mel<-arrange(mel,YEAR)
head(mel,20)
melloop<-ts(mel$value,frequency=12)
model<-Arima(melloop,order=c(0,0,0),seasonal=list(order=c(1,1,1),period=2))
pre<-forecast(model,h=6)
pre<-as.data.frame(pre)

ggplot(data=mel, aes(x=variable, y = value, colour = YEAR, group = YEAR)) + geom_line() + facet_wrap(~YEAR)